version: '3'
services:

    postgres:
        image: 'postgres:9.6-alpine'
        volumes:
            - postgres-volume:/var/lib/postgresql/data
        container_name: "postgres"
        ports:
            - 5433:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: cdc

    pgadmin4:
        image: 'dpage/pgadmin4:5.5'
        volumes:
            - pgadmin-volume:/var/lib/pgadmin
        container_name: "pgadmin4"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: pass123
        ports:
            - 8082:80

volumes:
    postgres-volume:
    pgadmin-volume: